"""Step 0c -- generate synthetic journal entries when real ones cannot be sourced.

Why this exists
---------------
Reddit requires a registered OAuth credential and blocks everything else (403,
confirmed with a policy-compliant User-Agent). The corpora reachable without one
carry 0.8-2.1% imposter-syndrome content, and Gemini labeled only 5 of 300 such
texts positive. There is no free path to enough real self-disclosure text.

There is, however, an argument that synthetic data is not merely a fallback
here: the app's real input is a **journal entry**, not a Reddit post. Reddit
prose -- titles, "edit:", replies to commenters, karma-aware framing -- was
always a domain mismatch with what the model will actually see in production.
Entries written in journal register are closer to deployment.

The one thing this cannot do is validate itself. See the honesty section below.

The register trap
-----------------
The obvious failure -- and the reason a lot of synthetic-data projects quietly
produce garbage -- is generating positives synthetically and taking negatives
from real text. The model then separates the classes on *register*, not
content: "reads like a journal" becomes the positive feature, and validation
accuracy looks superb while the model has learned nothing about imposter
syndrome.

So both classes are generated here, by the same model, from the same style
pool, with the same length distribution. The only thing that differs is what
the entry is about. Real text is still used, but only as EXTRA negatives after
the balanced core is in place, never as the sole source of them.

Honesty
-------
Labels here are correct by construction: we asked for a pattern and the
generator wrote it. That removes teacher noise but introduces something worse
if left unchecked -- the generator may not have expressed what was requested.
`--verify` runs the generated set back through label_data.py's annotation
prompt, and disagreement between requested and detected labels is a direct
measure of generation quality. Run it.

None of this makes the gold set synthetic-free. If you report numbers from a
model trained this way, say so: "positives generated by an LLM in journal
register, negatives generated the same way, gold set hand-labeled." That is a
publishable setup. Presenting it as trained on real self-disclosure is not.

Usage:
    python3 ml/synthesize.py --target 1500
    python3 ml/synthesize.py --verify
"""

import argparse
import hashlib
import json
import random
import time
import urllib.error
import urllib.request

from config import LABELS, LABEL_DESCRIPTIONS, RAW_DIR, SEED
from label_data import API_BASE, MODEL_CHAIN, QuotaExceeded, load_api_key

SYNTHETIC_PATH = RAW_DIR / "synthetic.jsonl"

PER_REQUEST = 8          # more than this and the entries start rhyming
DEFAULT_RPM = 10

# --- Diversity axes --------------------------------------------------------
# Without these, 1,500 entries collapse into about six templates wearing
# different hats. Each request draws a fresh combination.

ROLES = [
    "software engineer", "data analyst", "PhD student in biology", "UX designer",
    "junior doctor", "high school teacher", "marketing associate", "civil engineer",
    "nurse", "graduate researcher", "product manager", "accountant",
    "architect", "lab technician", "journalist", "social worker",
    "mechanical engineer", "pharmacist", "consultant", "translator",
]

STAGES = [
    "three weeks into a first job", "two years in and up for promotion",
    "recently promoted", "returning after a career break",
    "switching industries", "the most senior person on a small team",
    "the most junior person on a large team", "midway through a degree",
    "about to defend a thesis", "just finished a big project",
]

TRIGGERS = [
    "a code review", "a presentation to leadership", "a performance review",
    "a conference talk", "a difficult meeting", "a rejected proposal",
    "a piece of praise from a manager", "a colleague's promotion",
    "an onboarding week", "a mistake that reached production",
    "a client call that went badly", "an award or public recognition",
    "a question they could not answer", "a deadline they nearly missed",
]

STYLES = [
    "short and clipped, fragments rather than full sentences",
    "long and winding, one thought running into the next",
    "plain and factual, almost like notes",
    "warm and self-aware, gently teasing themselves",
    "raw and unfiltered, mid-feeling",
    "tired, written late at night",
    "analytical, trying to reason through what happened",
    "hopeful despite the day, ending on something small and good",
]

# Negative scenarios that are genuinely hard: real distress, no competence doubt.
# A model trained without these learns "sounds bad" and fires on every rough day.
NEGATIVE_TOPICS = [
    "exhausted by workload volume, but confident in their ability",
    "frustrated with a disorganised manager",
    "grieving a family member",
    "bored and under-stimulated at work",
    "anxious about rumoured layoffs, not about their own competence",
    "in conflict with a coworker over a decision, and sure they are right",
    "physically unwell and behind on everything",
    "proud of finishing something difficult",
    "lonely after relocating for a job",
    "annoyed by commute and office logistics",
    "stressed about money, unrelated to job performance",
    "happy about a good day, nothing to process",
    "worried about a friend going through a hard time",
    "irritated by a tool or process that keeps breaking",
    "content, reflecting on a quiet ordinary day",
]

# Label combinations to request. Weighted toward realistic co-occurrence --
# fear of exposure travels with comparison; luck travels with discounting praise.
POSITIVE_COMBOS = [
    ["attribution_to_luck"],
    ["fear_of_exposure"],
    ["discounting_praise"],
    ["overworking_to_compensate"],
    ["comparison_to_peers"],
    ["fear_of_exposure", "comparison_to_peers"],
    ["attribution_to_luck", "discounting_praise"],
    ["fear_of_exposure", "overworking_to_compensate"],
    ["comparison_to_peers", "attribution_to_luck"],
    ["discounting_praise", "fear_of_exposure"],
    ["overworking_to_compensate", "comparison_to_peers"],
    ["fear_of_exposure", "attribution_to_luck", "discounting_praise"],
]

# Asking one prompt to "vary the length" does not work -- the first run came
# back 561-925 chars with a median of 695, i.e. no variation at all. Drawing a
# band per request produces the spread that a single instruction cannot.
#
# This matters for deployment, not just realism: plenty of real entries are one
# tired line, and a model trained only on 700-character essays will not have
# seen anything resembling "rough day, didn't speak up in standup again".
LENGTH_BANDS = [
    "very short -- 1 or 2 sentences, under 200 characters, the kind of thing "
    "someone types before giving up and going to bed",
    "short -- 2 to 3 sentences, around 250 characters",
    "medium -- 4 to 5 sentences, around 450 characters",
    "long -- 6 to 8 sentences, around 800 characters, thoughts running on",
]

ENTRY_SCHEMA = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {"entry": {"type": "string"}},
        "required": ["entry"],
    },
}


def fingerprint(text):
    return hashlib.sha256(" ".join(text.lower().split()).encode()).hexdigest()[:16]


def build_prompt(rng, combo):
    role = rng.choice(ROLES)
    stage = rng.choice(STAGES)
    trigger = rng.choice(TRIGGERS)
    styles = rng.sample(STYLES, k=min(3, len(STYLES)))
    length = rng.choice(LENGTH_BANDS)

    if combo:
        patterns = "\n".join(f"  - {label}: {LABEL_DESCRIPTIONS[label]}" for label in combo)
        instruction = f"""Each entry MUST clearly express these patterns, and only these:

{patterns}

Express them the way a real person would -- implied through what they say about
themselves, not stated clinically. Nobody writes "I am attributing my success to
luck"; they write "the questions just happened to be ones I'd seen before"."""
    else:
        topic = rng.choice(NEGATIVE_TOPICS)
        instruction = f"""Each entry is about: {topic}

CRITICAL: these entries must contain NO imposter-syndrome patterns. The person
may be tired, sad, angry, overwhelmed or delighted -- but they must NOT doubt
their own competence, fear being exposed as a fraud, credit their success to
luck, deflect praise, or measure themselves as behind their peers.

This is the hard part of the dataset. A model that has not seen distressed
entries WITHOUT self-doubt will flag every bad day as imposter syndrome."""

    return f"""Write {PER_REQUEST} private journal entries, as if typed into a journaling app at the end of the day.

The writer is a {role}, {stage}. Something happened today involving {trigger}.

{instruction}

Requirements:
- First person, present-ish tense, written TO THEMSELVES. No greeting, no signoff.
- LENGTH: {length}. Hold to this -- do not drift longer.
- Vary the voice across the {PER_REQUEST} entries. Use these registers: {"; ".join(styles)}.
- Concrete and specific: name the meeting, the file, the person, the hour.
- No therapy-speak, no diagnosis words, never the phrase "imposter syndrome".
- Do not number them or add titles.
- These are different people, not one person over several days.

Return a JSON array of {PER_REQUEST} objects, each with an "entry" field."""


def generate(api_key, model, prompt):
    body = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "response_mime_type": "application/json",
            "response_schema": ENTRY_SCHEMA,
            # High temperature on purpose: this is the one call in the pipeline
            # where variety IS the product. Low temperature yields 1,500 entries
            # that read like one person with a thesaurus.
            "temperature": 1.15,
            "topP": 0.97,
        },
    }

    request = urllib.request.Request(
        f"{API_BASE}/{model}:generateContent?key={api_key}",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"},
    )

    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=180) as response:
                payload = json.load(response)
            break
        except urllib.error.HTTPError as error:
            if error.code == 429:
                raise QuotaExceeded(error.read().decode()[:150]) from error
            if error.code >= 500 and attempt < 3:
                time.sleep(5 * (attempt + 1))
                continue
            raise RuntimeError(f"HTTP {error.code}: {error.read().decode()[:150]}") from error
        except (urllib.error.URLError, TimeoutError):
            if attempt < 3:
                time.sleep(5 * (attempt + 1))
                continue
            raise
    else:
        raise RuntimeError("exhausted retries")

    text = payload["candidates"][0]["content"]["parts"][0]["text"]
    return json.loads(text)


def existing_fingerprints():
    if not SYNTHETIC_PATH.exists():
        return set()
    seen = set()
    with SYNTHETIC_PATH.open() as handle:
        for line in handle:
            if line.strip():
                try:
                    seen.add(fingerprint(json.loads(line)["text"]))
                except (json.JSONDecodeError, KeyError):
                    continue
    return seen


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", type=int, default=1500)
    parser.add_argument("--positive-fraction", type=float, default=0.55)
    parser.add_argument("--rpm", type=float, default=DEFAULT_RPM)
    parser.add_argument("--restart", action="store_true")
    args = parser.parse_args()

    api_key = load_api_key()
    if not api_key:
        raise SystemExit("GEMINI_API_KEY not found in the environment or .env")

    if args.restart and SYNTHETIC_PATH.exists():
        SYNTHETIC_PATH.unlink()

    seen = existing_fingerprints()
    print(f"{len(seen)} synthetic entries already generated")

    remaining = args.target - len(seen)
    if remaining <= 0:
        print("Target already met.")
        return

    rng = random.Random(SEED + len(seen))
    requests_needed = (remaining + PER_REQUEST - 1) // PER_REQUEST
    interval = 60.0 / args.rpm if args.rpm > 0 else 0

    print(f"Generating ~{remaining} more in {requests_needed} requests "
          f"(~{requests_needed * interval / 60:.0f} min)")

    model_index = 0
    positive_credit = 0.0
    written = 0
    label_counts = {label: 0 for label in LABELS}
    negatives = 0

    with SYNTHETIC_PATH.open("a") as out:
        for request_index in range(requests_needed):
            # Interleave positives and negatives so that EVERY prefix of the run
            # is balanced, not just the full run. The obvious `index % 100 <
            # fraction*100` produces 55 positives followed by 45 negatives, so a
            # run cut short by quota yields a file with no negatives at all --
            # which is exactly what the first 40-entry test produced.
            #
            # A fractional accumulator (Bresenham) gives P,N,P,N,P,P,N,... and
            # stays near the target ratio at any stopping point.
            positive_credit += args.positive_fraction
            want_positive = positive_credit >= 1.0
            if want_positive:
                positive_credit -= 1.0

            combo = rng.choice(POSITIVE_COMBOS) if want_positive else []

            started = time.time()
            entries = None

            while model_index < len(MODEL_CHAIN):
                try:
                    entries = generate(api_key, MODEL_CHAIN[model_index],
                                       build_prompt(rng, combo))
                    break
                except QuotaExceeded:
                    print(f"\n  {MODEL_CHAIN[model_index]} out of quota; next model")
                    model_index += 1
                except Exception as error:  # noqa: BLE001
                    # Advance on persistent failure too, not just on quota. A
                    # model that is 503-ing ("high demand") stays 503 for hours;
                    # retrying it forever stalls the whole run, which is exactly
                    # what happened the first time this was run.
                    print(f"\n  {MODEL_CHAIN[model_index]} failing ({error}); next model")
                    model_index += 1

            if model_index >= len(MODEL_CHAIN):
                print("\nAll models out of quota. Re-run tomorrow -- it resumes.")
                break
            if entries is None:
                continue

            for item in entries:
                text = " ".join((item.get("entry") or "").split())
                if len(text) < 60:
                    continue
                key = fingerprint(text)
                if key in seen:
                    continue
                seen.add(key)

                out.write(json.dumps({
                    "text": text,
                    "labels": {label: (label in combo) for label in LABELS},
                    "origin": "synthetic",
                    "generator": MODEL_CHAIN[model_index],
                }) + "\n")
                written += 1
                if combo:
                    for label in combo:
                        label_counts[label] += 1
                else:
                    negatives += 1

            out.flush()
            print(f"  {request_index + 1}/{requests_needed} requests, {written} entries",
                  end="\r", flush=True)

            elapsed = time.time() - started
            if interval > elapsed and request_index < requests_needed - 1:
                time.sleep(interval - elapsed)

    print(f"\n\nWrote {written} entries to {SYNTHETIC_PATH}")
    print(f"  negatives: {negatives}")
    for label, count in label_counts.items():
        print(f"  {label:<30} {count:>4}")
    print("\nNext: python3 ml/synthesize.py --verify   (checks the generator did")
    print("      what was asked; disagreement here is your data-quality number)")


if __name__ == "__main__":
    main()
